### ISSUE TITLE
The self-generated HTTPS certificate is not trusted

### ISSUE THREAD

**Issue by LBJSCC** [a-schild/nextcloud-java-api#25]
Hi, I'm from China.I built nextCloud in the local use is the certificate generated by their own, when using the API call method prompted: "General SSLEngine problem", "incapable to find valid certification path to requested target".I want to trust all the SSL certificates when I request, how should I do? Thank you very much for your advice

**Comment by LBJSCC** [comment]
Here's how I solved it.Configure the server's certificate into my JDK and no more SSL errors will be reported

**Comment by a-schild** [comment]
See this discussion:

https://stackoverflow.com/questions/2893819/accept-servers-self-signed-ssl-certificate-in-java-client

Currently I don't have plans to implement the ssl check disabling, but would accept a pull request if you provide an implementation.

I don't see a wide usage of such a patch, since nextcloud is intended to exchange files via webbrowser, and these will also all show warnings/errors too.
And in the times of letsenrypt ssl certificates don't cost money, or other providers have very cheap ssl prices.

**Comment by tobiasKaminsky** [comment]
> And in the times of letsenrypt ssl certificates don't cost money, or other providers have very cheap ssl prices.

:+1: having self signed certs seems to me like ancient workarounds ;-)
