### ISSUE TITLE
downloadFolder not working with special charater

### ISSUE THREAD

**Issue by flelayo** [a-schild/nextcloud-java-api#71]
We are using the org.aarboard.nextcloud.api.NextcloudConnector.downloadFolder function and had an issue with the special character. For example for the filename "MobaXterm backup.zip" sardine.exists gave us a malformated URI exception because space was not escaped.

We tried to use the buildWebdavPath but it seems complex to use as the function is called previously on the root path.
I will try to make the pull request work this time if not will edit the issue with the code we used to correct it.

Thanks

**Comment by flelayo** [comment]
Here is the diff [Folder.java.txt](https://github.com/a-schild/nextcloud-java-api/files/7346801/Folder.java.txt). there is some noise due to my IDE reformating

Unit test were not working (I added the setting.xml but still, wrong plugin version ?) so I disabled them and It will be hard to check if they work.

**Comment by a-schild** [comment]
Looks like it fixes the problem, thanks

Can you test with the 11.7.0-SNAPSHOT release?

**Comment by a-schild** [comment]
Yes, it should also solve the problem with login name not identical to the NC internal user name in issue #68 

The drawback is, that we have to ask the server what the user name of that user is, before we can work with files in NC, but there is no way to know this for sure, so that's the only real working solution.

**Comment by flelayo** [comment]
12.0.0 works fine, thanks
